
//---------- ----------------------------- ----------
//---------- !!! DONT CHANGE THIS FILE !!! ----------
//---------- ----------------------------- ----------
//---------- !!! AUTOGENERATED CONTENT !!! ----------
//---------- ----------------------------- ----------

//---------- ----------------------------- ----------
//---------- !!! IL2CPP AOT COMPILATION !! ----------
//---------- ----------------------------- ----------
//2022-04-21 22:48:29Z

internal class IL2CPP_AOT
{
    //FieldProfile<PlayerWeapon, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerWeapon, System.Int32> AOT_GENERATED_TYPE_0;
    
    //FieldUnit<PlayerWeapon, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerWeapon, System.Int32> AOT_GENERATED_TYPE_2;
    
    //FieldProfile<FPSMonitor, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Single> AOT_GENERATED_TYPE_4;
    
    //FieldUnit<FPSMonitor, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Single> AOT_GENERATED_TYPE_6;
    
    //FieldProfile<FPSMonitor, long>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int64> AOT_GENERATED_TYPE_8;
    
    //FieldUnit<FPSMonitor, long>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int64> AOT_GENERATED_TYPE_10;
    
    //FieldProfile<FPSMonitor, long>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int64> AOT_GENERATED_TYPE_12;
    
    //FieldUnit<FPSMonitor, long>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int64> AOT_GENERATED_TYPE_14;
    
    //PropertyProfile<VsyncMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.PropertyProfile<System.Object, System.Int32> AOT_GENERATED_TYPE_16;
    
    //PropertyUnit<VsyncMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.PropertyUnit<System.Object, System.Int32> AOT_GENERATED_TYPE_18;
    
    //PropertyProfile<VsyncMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.PropertyProfile<System.Object, System.Int32> AOT_GENERATED_TYPE_20;
    
    //PropertyUnit<VsyncMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.PropertyUnit<System.Object, System.Int32> AOT_GENERATED_TYPE_22;
    
}