// Copyright (c) 2022 Jonathan Lang

//---------- ----------------------------- ----------
//---------- !!! AUTOGENERATED CONTENT !!! ----------
//---------- ----------------------------- ----------

//Runtime Monitoring
//File generated: 2022-10-01 17:50:56Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT
{
    //Value Processor Method Definitions

    [UnityEngine.Scripting.PreserveAttribute]
    [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]
    private static void AOT()
    {
        // Field type definitions
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Example.Scripts.GameManager, System.Int32>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Int32>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Single>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Example.Scripts.PlayerWeapon, System.Int32>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Example.Scripts.ShootingTarget, System.Single>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Modules.FPSMonitor, System.Single>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<Baracuda.Monitoring.Modules.SystemMonitor, System.String>();

        // Property type definitions
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<Baracuda.Monitoring.Example.Scripts.GameManager, Baracuda.Monitoring.Example.Scripts.GameState>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<Baracuda.Monitoring.Example.Scripts.PlayerMovement, UnityEngine.Vector3>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<Baracuda.Monitoring.Modules.ConsoleMonitor, System.Collections.Generic.Queue<System.String>>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<Baracuda.Monitoring.Modules.ConsoleMonitor, System.String>();
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<Baracuda.Monitoring.Modules.FPSMonitor, System.Int32>();

        // Event type definitions
        Baracuda.Monitoring.Core.IL2CPP.IL2CPPTypeDefinitions.TypeDefEvent<Baracuda.Monitoring.Example.Scripts.GameManager, System.Action<Baracuda.Monitoring.Example.Scripts.GameState>>();

        // Method type definitions

        // Out Parameter type definitions
    }
}

#endif //ENABLE_IL2CPP && !DISABLE_MONITORING

//----------------------------------------------------------------------------------------------------------------------

//--- Stats ---

//General

//Monitored Member:               37
//Monitored Member Instance:      37

//MemberInfo

//Monitored Events:                1
//Monitored Events Instance:       1
//Monitored Fields:               30
//Monitored Fields Instance:      30
//Monitored Properties:            6
//Monitored Properties Instance:   6

//Monitored Types

//Monitored Action<GameState>:     1
//Monitored bool:                  3
//Monitored float:                 4
//Monitored GameState:             1
//Monitored int:                   5
//Monitored Queue<string>:         1
//Monitored string:               21
//Monitored Vector3:               1

//----------------------------------------------------------------------------------------------------------------------

//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring